apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo-erp
  template:
    metadata:
      labels:
        app: odoo-erp
    spec:
      containers:
      - name: odoo
        image: odoo:latest
        ports:
        - containerPort: 8069
        env:
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: odoo
        - name: DB_USER
          value: odoo
        - name: DB_PASSWORD
          value: pwd
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-erp
spec:
  selector:
    app: odoo-erp
  ports:
  - name: http
    port: 80
    targetPort: 8069
  type: LoadBalancer
